In [1]:
import cv2,numpy as np

img=cv2.imread("C:/Users/Abdul/Downloads/download (1).jpg")
img2=cv2.imread("C:/Users/Abdul/Downloads/download.jpg")
img3=cv2.imread("C:/Users/Abdul/Downloads/download1.jpg")



In [14]:
print(img.shape)
print(img.dtype)
print(img.ndim)


(225, 225, 3)
uint8
3


In [3]:
h, w = img.shape[:2]
total=h*w
total

50625

In [7]:
img.size

151875

In [5]:
bgr_pixel=img[200,206]
bgr_pixel

array([ 0, 16, 27], dtype=uint8)

In [13]:
img_f=img.astype('float32')
img_f

array([[[180., 200., 211.],
        [180., 200., 211.],
        [180., 200., 211.],
        ...,
        [179., 199., 210.],
        [179., 199., 210.],
        [178., 200., 211.]],

       [[180., 200., 211.],
        [180., 200., 211.],
        [180., 200., 211.],
        ...,
        [179., 199., 210.],
        [179., 199., 210.],
        [178., 200., 211.]],

       [[180., 200., 211.],
        [180., 200., 211.],
        [180., 200., 211.],
        ...,
        [179., 199., 210.],
        [179., 199., 210.],
        [178., 200., 211.]],

       ...,

       [[  6.,  46.,  51.],
        [  7.,  47.,  52.],
        [  7.,  47.,  52.],
        ...,
        [ 30.,  79.,  95.],
        [ 33.,  80.,  94.],
        [ 28.,  73.,  84.]],

       [[ 11.,  53.,  60.],
        [ 10.,  52.,  57.],
        [ 11.,  50.,  58.],
        ...,
        [  2.,  51.,  67.],
        [  3.,  52.,  66.],
        [ 21.,  67.,  78.]],

       [[ 10.,  57.,  65.],
        [ 14.,  60.,  67.],
        [ 26.,  

In [11]:
R=img[:,:,2]
B=img[:,:,0]
G=img[:,:,1]
print(R)

[[211 211 211 ... 210 210 211]
 [211 211 211 ... 210 210 211]
 [211 211 211 ... 210 210 211]
 ...
 [ 51  52  52 ...  95  94  84]
 [ 60  57  58 ...  67  66  78]
 [ 65  67  76 ...  59  65  61]]


In [19]:
cv2.imshow('Abdulla',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
gray=cv2.imread("C:/Users/Abdul/Downloads/download (1).jpg",0)
cv2.imshow('Abdulla',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
color=cv2.imread("C:/Users/Abdul/Downloads/download (1).jpg",1)
cv2.imshow('Abdulla',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
rgba=cv2.imread("C:/Users/Abdul/Downloads/download (1).jpg",-1)
cv2.imshow('Abdulla',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
new_img=cv2.imwrite('abdulla.jpg',img)
